import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import ProfilePic from "../../public/images/profile/BryanProfilePic.png";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import LightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Bryan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-center w-full">
            <div className="w-2/5 mr-20">
              <Image
                src={ProfilePic}
                alt="Bryan Khor"
                className="w-full h-auto rounded-full"
              ></Image>
            </div>
            <div className="w-1/2 ml-20 flex flex-col items-center self-center">
              <AnimatedText
                text="Shaping the future, one line of code at a time."
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                As a skilled web developer, I am dedicated to turning ideas into
                innovative web applications. Explore my latest projects and
                articles, showcasing my expertise in React.js and web
                development.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Bryan Frontend Engineer Resume.pdf"
                  target={"_blank"}
                  className="flex items center bg-dark text-light p-2.5 px-6 rounded-lg 
                  text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent
                  hover:border-dark"
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="bryankhor07@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={LightBulb} alt="Bryan Khor" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
