import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import { GithubIcon } from "@/components/Icons";
import OnlineRecipeApp from "../../public/images/projects/Recipe.ioHomePage.png";
import WeatherApp from "../../public/images/projects/WeatherAppPhoto.png";
import Tenzies from "../../public/images/projects/TenziesApp.png";
import ExpenseTracker from "../../public/images/projects/ExpenseTrackerPhoto.png";

const FeaturedProject = ({ type, title, summary, img, link, github }) => {
  return (
    <article
      className="w-full flex items-center justify-between rounded-3xl relative rounded-br-2xl
    border border-solid border-dark bg-light shadow-2xl p-12"
    >
      <div
        className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] bg-dark
      rounded-br-3xl"
      />
      <Link
        href={link}
        target="_blank"
        className="w-1/2 cursor-pointer overflow-hidden rounded-lg"
      >
        <Image src={img} alt={title} className="w-full h-auto" />
      </Link>

      <div className="w-1/2 flex flex-col items-start justify-between pl-6">
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset-2"
        >
          <h2 className="my-2 w-full text-left text-4xl font-bold">{title}</h2>
        </Link>
        <p className="my-2 font-medium text-dark">{summary}</p>
        <div className="mt-2 flex items-center">
          <Link href={github} target="_blank" className="w-10">
            <GithubIcon />
          </Link>
          <Link
            href={link}
            target="_blank"
            className="ml-4 rounded-lg bg-dark text-light p-2 px-6
          text-lg font-semibold"
          >
            Visit Project
          </Link>
        </div>
      </div>
    </article>
  );
};

const Project = ({ title, type, img, link, github }) => {
  return (
    <article
      className="w-full flex flex-col items-center justify-center rounded-2xl border border-solid
    border-dark bg-light p-6 relative"
    >
      <div
        className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark
      rounded-br-3xl"
      />
      <Link
        href={link}
        target="_blank"
        className="w-full cursor-pointer overflow-hidden rounded-lg"
      >
        <Image src={img} alt={title} className="w-full h-auto" />
      </Link>

      <div className="w-full flex flex-col items-start justify-between mt-4">
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset-2"
        >
          <h2 className="my-2 w-full text-left text-3xl font-bold">{title}</h2>
        </Link>
        <div className="w-full mt-2 flex items-center justify-between">
          <Link
            href={link}
            target="_blank"
            className="text-lg font-semibold underline"
          >
            Visit
          </Link>
          <Link href={github} target="_blank" className="w-8">
            {" "}
            <GithubIcon />{" "}
          </Link>
        </div>
      </div>
    </article>
  );
};

const Projects = () => {
  return (
    <>
      <Head>
        <title>Bryan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full mb-16 flex flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText text="Turning Ideas Into Reality" className="mb-16" />
          <div className="grid grid-cols-12 gap-24 gap-y-32">
            <div className="col-span-12">
              <FeaturedProject
                type="Featured Project"
                title="Online Recipe Application"
                summary="A recipe-sharing platform where users can explore, create, and
              favorite recipes. Features include dark mode, user ratings, user
              comments and a surprise recipe generator. Built using React,
              Firebase, and Cloud Firestore to deliver a dynamic and
              user-friendly experience."
                img={OnlineRecipeApp}
                link="https://online-recipe-19b1d.web.app/"
                github="https://github.com/bryankhor07/online-recipe-web-app"
              />
            </div>
            <div className="col-span-6">
              <Project
                type="Project"
                title="Weather App"
                summary="A weather app that displays the current weather, temperature, and
              humidity for a specific city. Created with React and styled with
              CSS for a clean and modern design."
                img={WeatherApp}
                link="https://easy-to-use-weatherapp.netlify.app/"
                github="https://github.com/bryankhor07/Weather-App"
              />
            </div>
            <div className="col-span-6">
              <Project
                type="Project"
                title="Tenzies"
                summary="A fun dice-rolling game where the goal is to match all the dice to
              the same number. Built with React for an interactive and
              responsive experience."
                img={Tenzies}
                link="https://tenziesgameforkids123.netlify.app/"
                github="https://github.com/bryankhor07/Tenzies-Game"
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                type="Featured Project"
                title="Expense Tracker"
                summary="An expense tracker that allows users to add and delete expenses,
              as well as view the total balance. Developed with React and
              Firebase for a seamless and efficient experience."
                img={ExpenseTracker}
                link="https://expense-tracker-c3464.web.app/"
                github="https://github.com/bryankhor07/expense-tracker"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default Projects;
